id: P009338
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:08.778902
source_metadata:
  id: bdr:W1KG9772
  title: སྡེ་དགེ་པར་ཁང་གི་དཀར་ཆག་ཞིབ་རྒྱས་སུ་བཀོད་པ་ཤེས་བྱའི་སྒོ་འབྱེད། ༼དཀྲུང་གོའི་བོད་ཀྱི་ཤེས་རིག་དཔེ་སྐྲུན་ཁང་།༽
  author: ''
  volumes:
    e39ce4332587442dbc5d3c7b7db859db:
      image_group_id: I1KG9795
      title: ''
      volume_number: 1
      total_pages: 718
      base_file: v001.txt
    10b8c1ca6ce447bc8046f390a6898465:
      image_group_id: I1KG9796
      title: ''
      volume_number: 2
      total_pages: 2
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
