id: P009338
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9772
  title: སྡེ་དགེ་པར་ཁང་གི་དཀར་ཆག་ཞིབ་རྒྱས་སུ་བཀོད་པ་ཤེས་བྱའི་སྒོ་འབྱེད། ༼དཀྲུང་གོའི་བོད་ཀྱི་ཤེས་རིག་དཔེ་སྐྲུན་ཁང་།༽
  author: ''
  volumes: {}
