id: I3BB4D02B
legacy_id: P009338
ocr_import_info:
  bdrc_scan_id: W1KG9772
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T21:39:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:38:26.442103+00:00'
last_modified: 2022-09-01 02:39:07.917209
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9772
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9772
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡེ་དགེ་པར་ཁང་གི་དཀར་ཆག་ཞིབ་རྒྱས་སུ་བཀོད་པ་ཤེས་བྱའི་སྒོ་འབྱེད། ༼དཀྲུང་གོའི་བོད་ཀྱི་ཤེས་རིག་དཔེ་སྐྲུན་ཁང་།༽
statistics:
  ocr_word_mean_confidence_index: 0.8594494621815442
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG9795:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9795
      total_pages: 718
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9795.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8593606439597726
    legacy_id: v001
  I1KG9796:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9796
      total_pages: 2
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9796.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9479024460948096
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
