id: I3BB4D02B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T21:39:43+00:00'
last_modified: '2022-06-08T10:18:30.317884+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9772
  title: སྡེ་དགེ་པར་ཁང་གི་དཀར་ཆག་ཞིབ་རྒྱས་སུ་བཀོད་པ་ཤེས་བྱའི་སྒོ་འབྱེད། ༼དཀྲུང་གོའི་བོད་ཀྱི་ཤེས་རིག་དཔེ་སྐྲུན་ཁང་།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B06:
      image_group_id: I1KG9795
      title: ''
      total_pages: 718
      order: 1
      base_file: 3B06.txt
    1E0B:
      image_group_id: I1KG9796
      title: ''
      total_pages: 2
      order: 2
      base_file: 1E0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
